---
site_name: Documentation

repo_url: https://github.com/dubas-pro/documentation/
edit_uri: edit/main/docs/
site_url: https://docs.dubas.pro/
site_author: dubas s.c.
site_description: >-
  Check out how to use the plugins for EspoCRM.
  Documentation contains detailed description of plugins prepared by dubas s.c. for EspoCRM.

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - mdx_truly_sane_lists
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - codehilite:
      guess_lang: false
      use_pygments: true
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  primary: indigo
  highlightjs: true
  logo: images/logo.png
  favicon: images/logo.png

  icon:
    repo: fontawesome/brands/github

  font:
    text: OpenSans

  palette:
    # Light mode
    - scheme: default
      media: '(prefers-color-scheme: light)'
      primary: white
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      media: '(prefers-color-scheme: dark)'
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tracking
    - content.tabs.link

nav:
  - Home: index.md
  - Extensions:
      - Installing Extensions: extensions/how-to-install.md
      - Premium:
        - Cal.com Integration: extensions/calcom.md
        - DAV Integration:
            - Overview: extensions/dav/index.md
            - Setting-up:
                - Setup: extensions/dav/setup.md
                - CardDAV: extensions/dav/carddav.md
                - CalDAV: extensions/dav/caldav.md
                - WebDAV: extensions/dav/webdav.md
            - Web Server:
                - Apache: extensions/dav/web-server/apache.md
                - Nginx: extensions/dav/web-server/nginx.md
        - GUS Integration: extensions/gus/index.md
        - PayPal Integration:
            - Overview: extensions/paypal/index.md
            - Transactions: extensions/paypal/transactions.md
            - Invoices: extensions/paypal/invoices.md
            - Payments: extensions/paypal/payments.md
            - Subscriptions: extensions/paypal/subscriptions.md
            - Products: extensions/paypal/products.md
            - Plans: extensions/paypal/plans.md
            - Webhooks: extensions/paypal/webhooks.md
        - QuickBooks Integration:
            - Overview: extensions/quickbooks/index.md
            # - Invoices: extensions/quickbooks/invoices.md
            # - Payments: extensions/quickbooks/payments.md
            - Projects: extensions/quickbooks/projects.md
            # - Employees: extensions/quickbooks/employees.md
            # - Purchase Orders: extensions/quickbooks/purchase-orders.md
            # - Webhooks: extensions/quickbooks/webhooks.md
        - Send: extensions/send.md
        - Stripe Integration:
            - Overview: extensions/stripe/index.md
            - Transactions: extensions/stripe/transactions.md
            - Sales Pack Invoices: extensions/stripe/invoices.md
        - Tawk.to Integration: extensions/tawk/index.md
        - VAT/VIES Integration: extensions/vies/index.md
        - Time Tracker:
            - Overview: extensions/time-tracker/index.md
            - Time Entries: extensions/time-tracker/time-entries.md
            - Time Trackers: extensions/time-tracker/time-trackers.md
            - Time Sessions: extensions/time-tracker/time-sessions.md
        - WooCommerce Integration: extensions/woocommerce/index.md
      - Open Source:
        - Address Field: extensions/address.md
        - Custom Formulas: extensions/custom-formulas.md
        - Google Fonts in PDF: extensions/google-fonts.md
        - Shipping Manager:
            - Overview: extensions/shipping-manager/index.md
            - Parcels: extensions/shipping-manager/parcels.md
            - Packages: extensions/shipping-manager/packages.md
            - Package Statuses: extensions/shipping-manager/package-statuses.md
            - Parcel Locations: extensions/shipping-manager/locations.md
        - Short Url: extensions/short-url.md
        - Template Helper: extensions/template-helper.md
        - UUID Field: extensions/uuid.md
      - Themes:
          - Light Theme: ./extensions/themes/light.md
          - Dark Theme: ./extensions/themes/dark.md
  - Videos:
      - Creating Email Templates: videos/how-to-create-email-template.md
      - Upgrading EspoCRM: videos/how-to-upgrade-espocrm.md
  - Contact & Support:
      - Contact: contact.md
      - How to buy our Extensions: extensions/how-to-buy.md
      - License: license.md
      - Versioning: versioning.md

plugins:
  - material/search
  - mkdocs-video

extra_javascript:
  - js/matomo.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dubas-pro
      name: Open Source on GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@devcrm
      name: Video Tutorials on YouTube

  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
      - manage
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: Copyright &copy; 2016 - <script>document.write(new Date().getFullYear())</script> dubas s.c. <br /> <a href="#__consent">Change cookie settings</a>
